A2K-Group-International/Project-UROBOROS

- src/App.jsx
- src/components/Family/EditParent.jsx
- src/components/Family/NewCoParent.jsx
- src/components/Home/Profile-Registration/FamilyRegistration.jsx
- src/components/Sidebar.jsx
- src/constants/roles.js
- src/constants/sidebarLinks.js
- src/context/UserContext.jsx
- src/hooks/Family/useRegisterCoParent.js
- src/hooks/useFamilyData.js
- src/pages/Events.jsx
- src/pages/Family.jsx
- src/services/authService.js
- src/services/familyService.js
- src/zodSchema/Family/RegisterCoParentSchema.js
-Parishioner can create co parent account
-Added Co Parent Role
-Removed Login need to confirm by admin
> Added Co Parent Account

- src/components/CommentComponents/EditReplyForm.jsx
- src/components/Loading.jsx
- src/components/Schedule/AddAttendee.jsx
- src/components/Schedule/AttendeeEditLogs.jsx
- src/components/Schedule/EditEvent.jsx
- src/components/Schedule/EventInfoDialog.jsx
- src/components/Schedule/MeetingDetails.jsx
- src/components/Schedule/ScheduleDetails.jsx
- src/components/ui/button.jsx
- src/hooks/useAnnouncements.js
- src/hooks/useRoleSwitcher.js
- src/pages/Announcements.jsx
- src/pages/Events.jsx
- src/pages/Ministries.jsx
- src/pages/Schedule.jsx
- src/services/attendanceService.js
- src/services/userService.js
added 1 week availability for editting
fixed download not showing
fixed edit family members bug after event finished added edit logs for each member and for each family
> Edit/Add Logs

- src/components/Calendar.jsx
- src/components/Events/ManualAttendEvents.jsx
- src/components/Events/ParishionerDialogCalendar.jsx
- src/components/Events/QRScannerEvents.jsx
- src/lib/utils.js
- src/pages/Events.jsx
- src/pages/Family.jsx
-Added Conditional Rendering Family Daata
-Added Date and Time in QR Scanned
-Fix QR Code not found
> Fix QR Code Scanned

- src/App.jsx
- src/components/Home/Profile-Registration/ParishionerRegister.jsx
- src/components/Login.jsx
- src/layouts/Landing-Layout.jsx
- src/pages/Privacy-Policy.jsx
-Rename the toast for registering
-Added privacy policy, terms and conditions.
-Disable registering button if not agreed.
> Added privacy-policy

- src/components/Announcements/Announcement.jsx
- src/components/Sidebar.jsx
- src/hooks/useRoleSwitcher.js
- src/pages/Announcements.jsx
fixed select overflow on create announcement
fixed bug where localstorage persist after logging out making sidebar buggy
> fixed bugs

- src/components/NewProfileForm.jsx
- src/pages/Home.jsx
- src/pages/Requests.jsx
- src/zodSchema/Request/NewUserSchema.js
-Change tagline under Homepage
-Remove Email input in edit profile under request page -Added Admin Tab
> Update Request Page

- src/App.jsx
- src/components/Ministry/AssignMembers.jsx
- src/components/Ministry/CreateMinistry.jsx
- src/components/Ministry/EditMinistry.jsx
- src/components/Ministry/MinistryCard.jsx
- src/components/Ministry/ViewMembers.jsx
- src/components/Schedule/ScheduleDetails.jsx
- src/components/Sidebar.jsx
- src/constants/sidebarLinks.js
- src/hooks/useMinistry.js
- src/pages/Ministries.jsx
- src/zodSchema/ManualAttendEventsSchema.js
-Fixed the height of the Parishioner Registration form on mobile devices. 
-Changed 'Admin Management Centre' to 'Children's Liturgy Management Centre.' 
-Added an admin feature for fetching and assigning volunteers. -Renamed 'All Ministries' to 'Groups.'
-Fixed the error display when editing a group.
-Removed the form error for not selecting a child.
> Hotfix 1-25-2025

- src/App.jsx
- src/components/Ministry/EditMinistry.jsx
- src/components/Schedule/ScheduleDetails.jsx
- src/constants/sidebarLinks.js
- src/pages/Ministries.jsx
-Reverted Groups to Ministries
-Adjust Schedule Details(Date) Font Size
> Hotfix 1-26-2025

- src/assets/icons/icons.jsx
- src/components/CommentComponents/ReplyInput.jsx
- src/components/Loading.jsx
- src/components/Request/FamilyCards.jsx
- src/components/Schedule/AddExistingRecord.jsx
- src/components/Schedule/AddFromRecord.jsx
- src/components/Schedule/AddRecord.jsx
- src/components/Schedule/AssignVolunteerComboBox.jsx
- src/components/Schedule/ScheduleDetails.jsx
- src/components/Schedule/VolunteerSelect.jsx
- src/hooks/Schedule/useAddRecord.js
- src/hooks/useLikeDislike.js
- src/lib/utils.js
- src/pages/Requests.jsx
- src/services/attendanceService.js
- src/services/familyService.js
- src/zodSchema/AddFamilySchema.js
added attending from family record in database
added attending  from database record for manual attendees
added search function in the families tab under request
updated forms to make parent optional
> Added adding attendance from record

- src/components/Ministry/CreateGroup.jsx
- src/components/Ministry/EditMinistry.jsx
- src/components/Ministry/MinistryCard.jsx
- src/components/Schedule/AddRecord.jsx
- src/components/Schedule/CreateEvent.jsx
- src/components/Schedule/EditAttendeeDialog.jsx
- src/hooks/useMinistry.js
- src/lib/utils.js
- src/pages/Ministries.jsx
- src/services/attendanceService.js
- src/services/ministryService.js
- src/zodSchema/CreateMinistrySchema.js
This pull request includes significant changes to the `Ministry` components and related files, focusing on renaming and refactoring the code to use the term "Group" instead of "Ministry". Additionally, some unused code has been commented out.
* `src/components/Ministry/CreateGroup.jsx` (renamed from `CreateMinistry.jsx`):
- Renamed component from `CreateMinistry` to `CreateGroup`. [[1]](diffhunk://#diff-5e86f97b3d194be06d52f7733ab08ccf3c75193f2ec837a9165732a290d6a0e1L28-R60) [[2]](diffhunk://#diff-5e86f97b3d194be06d52f7733ab08ccf3c75193f2ec837a9165732a290d6a0e1L73-R85)
- Updated text labels and placeholders to use "Group" instead of "Ministry".
- Commented out unused code related to coordinators and user queries. [[1]](diffhunk://#diff-5e86f97b3d194be06d52f7733ab08ccf3c75193f2ec837a9165732 …
> Hotfix 2 13 2025

- src/components/Request/AddChild.jsx
- src/components/Request/AddParent.jsx
- src/components/Request/FamilyCards.jsx
- src/components/Schedule/ScheduleDetails.jsx
This pull request includes changes to improve the user interface by adjusting button sizes and adding popover tooltips for better user guidance. The most important changes include modifications to `AddChild`, `AddParent`, `FamilyCards`, and `ScheduleDetails` components.
* [`src/components/Request/AddChild.jsx`](diffhunk://#diff-6feb32ead362e15aa824f296a0204a6c80442675d524f493f6d13343449dbdc1L79-R80): Adjusted the button size and icon dimensions for better visual consistency.
* [`src/components/Request/AddParent.jsx`](diffhunk://#diff-51f7fc97a2edd5f30603721af51a67a9a822486c99344f91216cc33f56ae4fc9L83-R84): Adjusted the button size and icon dimensions to match the changes made in `AddChild`.
* [`src/components/Request/FamilyCards.jsx`](diffhunk://#diff-5ea4c74ca363eca71d861493a230f61435d360 …
> Added a tooltip for Family Tab and Attendance

- src/components/Schedule/NewCreateEvent.jsx
- src/components/Schedule/NewEditEvent.jsx
This pull request includes changes to the `NewCreateEventForm` component in the `src/components/Schedule/NewCreateEvent.jsx` file. The changes focus on improving the responsiveness and styling of the `AlertDialogContent` and `AlertDialogTitle` elements.
Styling and responsiveness improvements:
* [`src/components/Schedule/NewCreateEvent.jsx`](diffhunk://#diff-5bd57c6ed64a5d16a9d31cb48688c05db6784604a278a14ba5d08a708dc430d0L291-R295): Modified the `AlertDialogContent` class to be more responsive by changing its width properties to `w-auto max-w-4xl sm:w-full`.
* [`src/components/Schedule/NewCreateEvent.jsx`](diffhunk://#diff-5bd57c6ed64a5d16a9d31cb48688c05db6784604a278a14ba5d08a708dc430d0L291-R295): Added padding to the `AlertDialogTitle` class by setting `p-0` to ensure proper spacing.
> Fix width for smaller screens

- src/services/attendanceService.js
This pull request includes several changes to the `searchAttendee` function in `src/services/attendanceService.js` to improve data normalization, filtering, and counting logic. The most important changes include trimming whitespace from names, normalizing and filtering walk-in attendees, and updating the total counts and combined results.
Normalization and filtering improvements:
* Trimmed whitespace from `first_name` and `last_name` for parents, children, and walk-ins. [[1]](diffhunk://#diff-79c0a730a4af177e7346f79ff592f1d93b08617c498503e2a938de4123e8e0faR866-R867) [[2]](diffhunk://#diff-79c0a730a4af177e7346f79ff592f1d93b08617c498503e2a938de4123e8e0faR878-R910)
* Created a normalized list of walk-ins and ensured unique entries by checking against existing names from parents and children. …
> Fix add from record

- src/pages/Feedback.jsx
- src/services/feedBackService.js
-Add search params for status
-Implement filtering feature
> Add filtering of status

- src/components/Announcements/Announcement.jsx
- src/components/Announcements/AnnouncementModal.jsx
- src/components/Calendar.jsx
- src/components/CommentComponents/CommentDetails.jsx
- src/components/CommentComponents/Replies.jsx
- src/components/CommentComponents/ReplyInput.jsx
- src/components/CommentComponents/SetShowReplyButton.jsx
- src/components/Comments.jsx
- src/components/Events/EventCard.jsx
- src/components/Events/FamilyData.jsx
- src/components/Events/ManualAttendEvents.jsx
- src/components/Events/QRScannedFamilyData.jsx
- src/components/Notification.jsx
- src/components/Schedule/ScheduleDetails.jsx
- src/hooks/useComment.js
- src/hooks/useNotification.js
- src/lib/utils.js
- src/pages/Events.jsx
- src/services/AnnouncementsService.js
- src/services/commentsService.js
- src/services/notificationService.js
This pull request introduces several updates to enhance the robustness and functionality of the `Announcement` and `Comment` components. The main changes include adding null safety to prevent potential runtime errors, introducing support for highlighting comments and replies based on URL parameters, and improving the `AnnouncementModal` to handle additional query parameters. Below are the most significant changes grouped by theme:
* Added optional chaining (`?.`) to various `announcement` and `announcement_files` properties in `Announcement.jsx` to prevent runtime errors when properties are undefined or null. [[1]](diffhunk://#diff-a69dc01f6118dcc2be591f23655cd28e3d4af3ea368885156508d35b0cae1b90L55-R55) [[2]](diffhunk://#diff-a69dc01f6118dcc2be591f23655cd28e3d4af3ea368885156508d35b0cae1b90 …
> Enhance Notification Feature

- src/lib/utils.js
- src/services/familyService.js
- src/services/userService.js
This pull request refactors filter handling in the `paginate` function and updates related service functions to improve consistency and simplify the codebase. The most notable changes include removing redundant or custom filter logic, standardizing the `in` filter format, and updating service functions to align with these changes.
* Removed the redundant handling of `filters.in` and moved its application earlier in the function to streamline logic. (`src/lib/utils.js`, [[1]](diffhunk://#diff-92cce0cb22d70a3bca04314e4aa8ad6dd742f7030ceaab2ffd35ad13cde99c55R65-R71) [[2]](diffhunk://#diff-92cce0cb22d70a3bca04314e4aa8ad6dd742f7030ceaab2ffd35ad13cde99c55L81-R88)
* Removed the custom `is_confirmed` filter logic (`filters.active`) to encourage using standard filters passed from the service …
> Hotfix Requests page

- src/components/Request/AddCategory.jsx
- src/components/Request/CategoryList.jsx
- src/components/Request/DeleteCategory.jsx
- src/components/Request/UserList.jsx
- src/components/Schedule/NewCreateEvent.jsx
- src/components/Schedule/NewEditEvent.jsx
- src/hooks/useCategory.js
- src/pages/Requests.jsx
- src/services/categoryServices.js
- src/zodSchema/CreateEventSchema.js
- src/zodSchema/EditEventSchema.js
This pull request introduces functionality for managing categories, including creating, editing, deleting, and listing categories, as well as integrating categories into event forms. The most significant changes include the addition of new components for category management, updates to event forms to dynamically load categories, and enhancements to the user interface for better usability.
* **AddCategory Component (`src/components/Request/AddCategory.jsx`)**: Implements a form for adding or editing categories, with validation using `zod` and support for both creation and updating workflows. Includes a dialog-based UI and integration with mutation hooks for API calls.
* **DeleteCategory Component (`src/components/Request/DeleteCategory.jsx`)**: Adds a confirmation dialog for deleting …
> Feature: Event Category

- src/App.jsx
- src/components/Consultation/ConsultationButton.jsx
- src/components/Consultation/ConsultationDialog.jsx
- src/components/Consultation/ConsultationQuestion.jsx
- src/components/Sidebar.jsx
- src/layouts/main-layout.jsx
- src/lib/utils.js
- src/pages/Consultation.jsx
- src/services/consultationServices.js
This pull request introduces a new "Consultation" feature, updates route configurations, and refines utility functions. The most significant changes include adding components for the consultation feature, reorganizing route access, and enhancing the `paginate` utility function with additional filtering capabilities.
* Added a `ConsultationButton` component for navigation, with separate designs for mobile and desktop views (`src/components/Consultation/ConsultationButton.jsx`).
* Introduced a `ConsultationDialog` component for user interaction, including animations and a close handler (`src/components/Consultation/ConsultationDialog.jsx`).
* Added a `ConsultationQuestion` component to handle form submissions with validation, ranking logic, and backend integration …
> Feature: Consultation

- src/components/Announcements/Announcement.jsx
- src/components/Home/Profile-Registration/ParishionerRegister.jsx
- src/components/Ministry/CoordinatorViewMinistry.jsx
- src/lib/ImageLoader.jsx
This pull request introduces updates to improve the user interface and functionality across several components in the codebase. Key changes include adjustments to styling for better responsiveness, updates to default states, and the addition of new content and tabs for enhanced user experience.
* [`src/components/Announcements/Announcement.jsx`](diffhunk://#diff-a69dc01f6118dcc2be591f23655cd28e3d4af3ea368885156508d35b0cae1b90L296-R296): Removed the `h-[100dvh]` class from the `ImageLoader` component to improve responsiveness and ensure the image scales better within the card.
* [`src/lib/ImageLoader.jsx`](diffhunk://#diff-52632b51013a12aa3057aa7b3afaec1b06f03cb2cbeaa394d6362ed6a135e15eL9-R9): Added `h-full object-contain` to the wrapper `div` in the `ImageLoader` component for consistent …
> Enhancement June 06, 2025

- src/components/Consultation/ConsultationButton.jsx
- src/pages/Consultation.jsx
- src/services/ministryService.js
This pull request includes changes to refactor and simplify code across multiple files, focusing on removing unused features, commenting out unused logic, and improving data processing in the `getMinistryGroups` function. The most important changes are grouped into two themes: **Code Cleanup** and **Data Processing Enhancements**.
* **Commented Out Unused Logic in `ConsultationButton` Component**: Removed unused imports, query logic, and conditional rendering related to consultation existence checks. This simplifies the component and removes dependencies on external services. (`src/components/Consultation/ConsultationButton.jsx`, [[1]](diffhunk://#diff-4948c30e12b7d8ebad429b8111b8b9effc385f80ee860be3efab2a51f111177aL5-R23) [[2]](diffhunk://#diff-4948c30e12b7d8ebad429b8111b8b9effc385f80ee86 …
> Close Consultation & Fix Image not fetching in Groups

- src/App.jsx
- src/components/Consultation/ConsultationButton.jsx
- src/components/Poll-List/PollList.jsx
- src/components/Poll-List/PollListCard.jsx
- src/components/Poll-List/PollListInformation.jsx
- src/components/Poll-Management/Addpoll.jsx
- src/components/Poll-Management/PollInformation.jsx
- src/components/Poll-Management/Pollcard.jsx
- src/components/Poll-Management/VoteResults.jsx
- src/components/Sidebar.jsx
- src/components/ui/carousel.jsx
- src/components/ui/dialog.jsx
- src/constants/sidebarLinks.js
- src/hooks/usePoll.js
- src/pages/Consultation.jsx
- src/pages/Poll.jsx
- src/services/groupServices.js
- src/services/ministryService.js
- src/services/pollServices.js
This pull request introduces changes across multiple components to enhance poll-related functionality, improve user experience, and simplify code. The most significant updates include refactoring the `PollListInformation` component to handle dynamic poll entries and votes, adding support for editing polls in the `Addpoll` component, and modifying the `PollList` layout for better usability.
* **Dynamic Poll Entries and Voting**: Refactored `PollListInformation` to fetch and display poll dates and times dynamically, allowing users to vote on individual time slots. Added optimistic updates and error handling for poll answers using React Query and mutation hooks. [[1]](diffhunk://#diff-684254ffa43d006058997b46b5072e73ed952b46084df4e11680cf7332b4bb98L60-R68) …
> Feature/ Poll Results

- src/components/CustomReactSelect.jsx
- src/components/Poll-Management/Addpoll.jsx
- src/services/pollServices.js
Added fetching of participants in edit poll
> Feat: Edit Poll Participants

- src/App.jsx
- src/pages/LicenseVerification.jsx
- src/pages/LicenseVerificationError.jsx
- src/pages/LicenseVerificationSuccess.jsx
This pull request introduces a license verification feature to the application. It includes new pages for verifying licenses, handling verification errors, and displaying success messages, as well as updates to the routing in `src/App.jsx`. The changes aim to streamline the user experience for license validation.
* Added routes for license verification, success, and error pages in `src/App.jsx`.
* Imported the new pages (`LicenseVerification`, `LicenseVerificationSuccess`, and `LicenseVerificationError`) in `src/App.jsx`.
* **License Verification Page (`src/pages/LicenseVerification.jsx`)**:
- Implements token validation, license verification logic, and dynamic UI states based on token validity.
* **License Verification Error Page (`src/pages/LicenseVerificationError.jsx`)**:
- Displays …
> feat: verify-license

- package-lock.json
- package.json
- src/components/ChangeProfile.jsx
- src/components/Sidebar.jsx
- src/hooks/useProfile.js
- src/pages/Profile.jsx
- src/services/authService.js
Introduces the ability for users to upload, update, and remove their profile pictures. Adds a new ChangeProfile component for handling image selection and preview, integrates image compression, and updates the Sidebar and Profile pages to display the user's profile image. Updates useProfile hook and authService to support profile picture storage and management using Supabase. Adds 'browser-image-compression' dependency.
> Add profile picture upload and removal feature
